print ("===========================================================")
print             (" SELAMAT DATANG DI PYTHON")
print ("============================================================")
print()
print("progam ini di buat oleh:",")(ochta setyawan)")
print("sekolah smk tjp tuban")
print("tahun   :",2026)
print(10+5)
print(20-8)
print(4*7)
